version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbapp
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  nestjs:
    image: lucaspscheidtunc/nestjs-server:1.0
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  db_data:
